//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int AuditLogId { get; set; }
        public string TableName { get; set; }
        public int RecordId { get; set; }
        public string Action { get; set; }
        public string OldValues { get; set; }
        public string NewValues { get; set; }
        public string ChangedFields { get; set; }
        public Nullable<int> UtilisateurId { get; set; }
        public string NomUtilisateur { get; set; }
        public System.DateTime DateAction { get; set; }
        public string AdresseIP { get; set; }
        public string UserAgent { get; set; }
    }
}
