//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotisationAnnuelle
    {
        public int CotisationAnnuelleId { get; set; }
        public int MedecinId { get; set; }
        public short AnneeExercice { get; set; }
        public Nullable<int> CodeCotisationId { get; set; }
        public string DescriptionSource { get; set; }
        public Nullable<decimal> MontantInitial { get; set; }
        public Nullable<bool> ReductionAppliquee { get; set; }
        public string MotifReduction { get; set; }
        public Nullable<decimal> MontantReduction { get; set; }
        public Nullable<bool> PenaliteAppliquee { get; set; }
        public string PenaliteTexte { get; set; }
        public Nullable<decimal> MontantPenalite { get; set; }
        public Nullable<decimal> MontantFinal { get; set; }
        public string EtatCotisation { get; set; }
        public Nullable<decimal> MontantPaye { get; set; }
        public Nullable<System.DateTime> DatePaiement { get; set; }
        public string TypePaiementTexte { get; set; }
        public Nullable<int> TypePaiementId { get; set; }
        public Nullable<System.DateTime> DateDepot { get; set; }
        public string NoDepot { get; set; }
        public string RecuImposition { get; set; }
        public Nullable<System.DateTime> DateRecuImposition { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual CodeCotisation CodeCotisation { get; set; }
        public virtual Medecin Medecin { get; set; }
        public virtual TypePaiement TypePaiement { get; set; }
    }
}
