//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DossierPrivilegeDecision
    {
        public int DossierPrivilegeDecisionId { get; set; }
        public int DossierPrivilegeId { get; set; }
        public int InstanceDecisionId { get; set; }
        public string TexteDecision { get; set; }
    
        public virtual DossierPrivilege DossierPrivilege { get; set; }
        public virtual InstanceDecision InstanceDecision { get; set; }
    }
}
