//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DossierPrivilege
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DossierPrivilege()
        {
            this.DossierPrivilegeDecision = new HashSet<DossierPrivilegeDecision>();
        }
    
        public int DossierPrivilegeId { get; set; }
        public int MedecinId { get; set; }
        public string EngagementFDC { get; set; }
        public Nullable<System.DateTime> DateAdhesionFDC { get; set; }
        public Nullable<System.DateTime> DateFinFDC { get; set; }
        public Nullable<System.DateTime> DateAvisCongeDepart { get; set; }
        public string AbsenceTemporaire { get; set; }
        public Nullable<System.DateTime> DateAbsence { get; set; }
        public Nullable<System.DateTime> DateRetourAbsence { get; set; }
        public string ListeNomin { get; set; }
        public string Engagement { get; set; }
        public Nullable<System.DateTime> DateDebutPratique { get; set; }
        public Nullable<System.DateTime> DateFinPrivileges { get; set; }
        public Nullable<System.DateTime> DateFinPratique { get; set; }
        public string PEMVise { get; set; }
        public string PEMAilleurs { get; set; }
        public string RLS { get; set; }
        public string PrivilegesTexte { get; set; }
        public string PrivilegesEnseignement { get; set; }
        public string PrivilegesRecherche { get; set; }
        public Nullable<System.DateTime> DemandeMSSS { get; set; }
        public Nullable<System.DateTime> ApprobMSSS { get; set; }
        public Nullable<System.DateTime> DemandeUdeM { get; set; }
        public Nullable<System.DateTime> ApprobUdeM { get; set; }
        public Nullable<System.DateTime> DateDMSP { get; set; }
        public Nullable<System.DateTime> DateCECMDP { get; set; }
        public Nullable<System.DateTime> DateCA { get; set; }
        public string NumeroResolution { get; set; }
        public Nullable<System.DateTime> DateRenouvellement { get; set; }
        public bool EstDossierActif { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual Medecin Medecin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DossierPrivilegeDecision> DossierPrivilegeDecision { get; set; }
    }
}
