//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntenteFDC
    {
        public int EntenteFDCId { get; set; }
        public int MedecinId { get; set; }
        public string TypeEntenteFDC { get; set; }
        public Nullable<System.DateTime> DateAdhesion { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string PEMVise { get; set; }
        public bool EstActive { get; set; }
    
        public virtual Medecin Medecin { get; set; }
    }
}
