//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FitTest
    {
        public int FitTestId { get; set; }
        public int MedecinId { get; set; }
        public string Resultat { get; set; }
        public Nullable<System.DateTime> DateFitTest { get; set; }
        public string Commentaire { get; set; }
        public bool EstActif { get; set; }
    
        public virtual Medecin Medecin { get; set; }
    }
}
