//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstanceDecision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstanceDecision()
        {
            this.DossierPrivilegeDecision = new HashSet<DossierPrivilegeDecision>();
        }
    
        public int InstanceDecisionId { get; set; }
        public int TypeInstanceDecisionId { get; set; }
        public string CodeInstance { get; set; }
        public Nullable<System.DateTime> DateInstance { get; set; }
        public string LibelleInstance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DossierPrivilegeDecision> DossierPrivilegeDecision { get; set; }
        public virtual TypeInstanceDecision TypeInstanceDecision { get; set; }
    }
}
