//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalImport
    {
        public int JournalImportId { get; set; }
        public string NomFichier { get; set; }
        public System.DateTime DateImport { get; set; }
        public Nullable<int> LignesImportees { get; set; }
        public Nullable<int> LignesRejetees { get; set; }
        public string Commentaire { get; set; }
    }
}
