//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedecinUniteOrganisationnelle
    {
        public int MedecinUniteOrganisationnelleId { get; set; }
        public int MedecinId { get; set; }
        public int UniteOrganisationnelleId { get; set; }
        public Nullable<byte> RangSource { get; set; }
        public string RoleOrganisationnel { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
    
        public virtual Medecin Medecin { get; set; }
        public virtual UniteOrganisationnelle UniteOrganisationnelle { get; set; }
    }
}
