//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medecin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medecin()
        {
            this.CotisationAnnuelle = new HashSet<CotisationAnnuelle>();
            this.DossierPrivilege = new HashSet<DossierPrivilege>();
            this.EntenteFDC = new HashSet<EntenteFDC>();
            this.FitTest = new HashSet<FitTest>();
            this.MedecinAdresse = new HashSet<MedecinAdresse>();
            this.MedecinComite = new HashSet<MedecinComite>();
            this.MedecinCourriel = new HashSet<MedecinCourriel>();
            this.MedecinInstallation = new HashSet<MedecinInstallation>();
            this.MedecinProfilCEMTL = new HashSet<MedecinProfilCEMTL>();
            this.MedecinTelephone = new HashSet<MedecinTelephone>();
            this.MedecinUniteOrganisationnelle = new HashSet<MedecinUniteOrganisationnelle>();
            this.NominationAdministrative = new HashSet<NominationAdministrative>();
            this.MedecinPrivilege = new HashSet<MedecinPrivilege>();
        }
    
        public int MedecinId { get; set; }
        public string Permis { get; set; }
        public Nullable<int> TitreId { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<int> TypePermisId { get; set; }
        public Nullable<int> StatutMedecinId { get; set; }
        public Nullable<int> CategoriePratiqueId { get; set; }
        public Nullable<int> GenreId { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public string NAM { get; set; }
        public Nullable<System.DateTime> DateEntreeFonction { get; set; }
        public Nullable<System.DateTime> DateDepart { get; set; }
        public string Commentaires { get; set; }
        public bool EstActif { get; set; }
        public System.DateTime DateCreation { get; set; }
        public System.DateTime DateModification { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotisationAnnuelle> CotisationAnnuelle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DossierPrivilege> DossierPrivilege { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntenteFDC> EntenteFDC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FitTest> FitTest { get; set; }
        public virtual CategoriePratique CategoriePratique { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual StatutMedecin StatutMedecin { get; set; }
        public virtual TitreMedecin TitreMedecin { get; set; }
        public virtual TypePermis TypePermis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedecinAdresse> MedecinAdresse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedecinComite> MedecinComite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedecinCourriel> MedecinCourriel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedecinInstallation> MedecinInstallation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedecinProfilCEMTL> MedecinProfilCEMTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedecinTelephone> MedecinTelephone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedecinUniteOrganisationnelle> MedecinUniteOrganisationnelle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NominationAdministrative> NominationAdministrative { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedecinPrivilege> MedecinPrivilege { get; set; }
    }
}
