//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedecinCourriel
    {
        public int MedecinCourrielId { get; set; }
        public int MedecinId { get; set; }
        public string TypeCourriel { get; set; }
        public string AdresseCourriel { get; set; }
        public Nullable<byte> RangSource { get; set; }
        public bool EstPrincipal { get; set; }
    
        public virtual Medecin Medecin { get; set; }
    }
}
