//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedecinInstallation
    {
        public int MedecinInstallationId { get; set; }
        public int MedecinId { get; set; }
        public int InstallationId { get; set; }
        public byte RangInstallation { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public bool EstPrincipale { get; set; }
    
        public virtual Installation Installation { get; set; }
        public virtual Medecin Medecin { get; set; }
    }
}
