//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedecinAdresse
    {
        public int MedecinAdresseId { get; set; }
        public int MedecinId { get; set; }
        public string AdresseLigne1 { get; set; }
        public string Ville { get; set; }
        public string Province { get; set; }
        public string CodePostal { get; set; }
        public bool EstPrincipale { get; set; }
    
        public virtual Medecin Medecin { get; set; }
    }
}
