//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedecinComite
    {
        public int MedecinComiteId { get; set; }
        public int MedecinId { get; set; }
        public int ComiteId { get; set; }
        public string RoleMembre { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string Commentaire { get; set; }
    
        public virtual Comite Comite { get; set; }
        public virtual Medecin Medecin { get; set; }
    }
}
