//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedecinPrivilege
    {
        public int MedecinPrivilegeId { get; set; }
        public int MedecinId { get; set; }
        public int PrivilegeReferenceId { get; set; }
        public Nullable<int> InstallationId { get; set; }
        public Nullable<int> UniteOrganisationnelleId { get; set; }
        public System.DateTime DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string Etat { get; set; }
        public string NatureActivites { get; set; }
        public string ChampActivites { get; set; }
        public string Obligations { get; set; }
        public string Commentaire { get; set; }
        public string NumeroResolutionCA { get; set; }
        public Nullable<System.DateTime> DateResolutionCA { get; set; }
        public bool ReconnaissanceEcriteRecue { get; set; }
        public bool EstActif { get; set; }
        public System.DateTime DateCreation { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
    
        public virtual Installation Installation { get; set; }
        public virtual Medecin Medecin { get; set; }
        public virtual PrivilegeReference PrivilegeReference { get; set; }
        public virtual UniteOrganisationnelle UniteOrganisationnelle { get; set; }
    }
}
