//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedecinProfilCEMTL
    {
        public int MedecinProfilCEMTLId { get; set; }
        public int MedecinId { get; set; }
        public string Telephone1 { get; set; }
        public string CellulaireNo { get; set; }
        public string Telephone2 { get; set; }
        public string DomicileNo { get; set; }
        public string Telephone3 { get; set; }
        public string PagetteNo { get; set; }
        public string Departement1 { get; set; }
        public string Departement2 { get; set; }
        public string ServiceSecteur1 { get; set; }
        public string ServiceSecteur2 { get; set; }
        public string Installation1Source { get; set; }
        public string Installation2Source { get; set; }
        public string Installation3Source { get; set; }
        public string Courriel1 { get; set; }
        public string Courriel2 { get; set; }
        public string CourrielMed { get; set; }
        public string NominationAdministrativeCourante { get; set; }
        public Nullable<System.DateTime> DateNominationAdministrative { get; set; }
        public Nullable<System.DateTime> DateAvisCongeDepart { get; set; }
        public string AbsenceTemporaire { get; set; }
        public Nullable<System.DateTime> DateAbsence { get; set; }
        public Nullable<System.DateTime> DateRetourAbsence { get; set; }
        public Nullable<System.DateTime> DateDebutPratique { get; set; }
        public Nullable<System.DateTime> DateFinPratique { get; set; }
        public string EngagementFDC { get; set; }
        public Nullable<System.DateTime> DateAdhesionFDC { get; set; }
        public Nullable<System.DateTime> DateFinFDC { get; set; }
        public string PEMVise { get; set; }
        public string PEMAilleurs { get; set; }
        public string RLS { get; set; }
        public string ListeNomin { get; set; }
        public string Engagement { get; set; }
        public string PrivilegesTexte { get; set; }
        public string PrivilegesEnseignement { get; set; }
        public string PrivilegesRecherche { get; set; }
        public Nullable<System.DateTime> DemandeMSSS { get; set; }
        public Nullable<System.DateTime> ApprobMSSS { get; set; }
        public Nullable<System.DateTime> DemandeUdeM { get; set; }
        public Nullable<System.DateTime> ApprobUdeM { get; set; }
        public Nullable<System.DateTime> DateDMSP { get; set; }
        public Nullable<System.DateTime> DateCECMDP { get; set; }
        public Nullable<System.DateTime> DateCA { get; set; }
        public string NumeroResolution { get; set; }
        public Nullable<System.DateTime> DateRenouvellement { get; set; }
        public string FitTestCourant { get; set; }
        public string CommentairesOperationnels { get; set; }
        public System.DateTime DateMajProfil { get; set; }
    
        public virtual Medecin Medecin { get; set; }
    }
}
