//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HopitalMedecinsDbEntities : DbContext
    {
        public HopitalMedecinsDbEntities()
            : base("name=HopitalMedecinsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AuditLog> AuditLog { get; set; }
        public virtual DbSet<CodeCotisation> CodeCotisation { get; set; }
        public virtual DbSet<Comite> Comite { get; set; }
        public virtual DbSet<CotisationAnnuelle> CotisationAnnuelle { get; set; }
        public virtual DbSet<DossierPrivilege> DossierPrivilege { get; set; }
        public virtual DbSet<DossierPrivilegeDecision> DossierPrivilegeDecision { get; set; }
        public virtual DbSet<EntenteFDC> EntenteFDC { get; set; }
        public virtual DbSet<FitTest> FitTest { get; set; }
        public virtual DbSet<Installation> Installation { get; set; }
        public virtual DbSet<InstanceDecision> InstanceDecision { get; set; }
        public virtual DbSet<JournalImport> JournalImport { get; set; }
        public virtual DbSet<Medecin> Medecin { get; set; }
        public virtual DbSet<MedecinAdresse> MedecinAdresse { get; set; }
        public virtual DbSet<MedecinComite> MedecinComite { get; set; }
        public virtual DbSet<MedecinCourriel> MedecinCourriel { get; set; }
        public virtual DbSet<MedecinInstallation> MedecinInstallation { get; set; }
        public virtual DbSet<MedecinProfilCEMTL> MedecinProfilCEMTL { get; set; }
        public virtual DbSet<MedecinTelephone> MedecinTelephone { get; set; }
        public virtual DbSet<MedecinUniteOrganisationnelle> MedecinUniteOrganisationnelle { get; set; }
        public virtual DbSet<Nomination> Nomination { get; set; }
        public virtual DbSet<NominationAdministrative> NominationAdministrative { get; set; }
        public virtual DbSet<TypeInstanceDecision> TypeInstanceDecision { get; set; }
        public virtual DbSet<TypeNomination> TypeNomination { get; set; }
        public virtual DbSet<TypePaiement> TypePaiement { get; set; }
        public virtual DbSet<UniteOrganisationnelle> UniteOrganisationnelle { get; set; }
        public virtual DbSet<UtilisateurMetier> UtilisateurMetier { get; set; }
        public virtual DbSet<CategoriePratique> CategoriePratique { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<StatutMedecin> StatutMedecin { get; set; }
        public virtual DbSet<TitreMedecin> TitreMedecin { get; set; }
        public virtual DbSet<TypePermis> TypePermis { get; set; }
        public virtual DbSet<vw_CotisationsParAnnee> vw_CotisationsParAnnee { get; set; }
        public virtual DbSet<vw_MedecinsRegistreCourant> vw_MedecinsRegistreCourant { get; set; }
        public virtual DbSet<MedecinPrivilege> MedecinPrivilege { get; set; }
        public virtual DbSet<PrivilegeReference> PrivilegeReference { get; set; }
    }
}
