//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominationAdministrative
    {
        public int NominationAdministrativeId { get; set; }
        public int MedecinId { get; set; }
        public string LibelleNomination { get; set; }
        public Nullable<System.DateTime> DateNomination { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public bool EstActive { get; set; }
        public Nullable<int> NominationId { get; set; }
        public Nullable<int> TypeNominationId { get; set; }
    
        public virtual Medecin Medecin { get; set; }
        public virtual Nomination Nomination { get; set; }
        public virtual TypeNomination TypeNomination { get; set; }
    }
}
