//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivilegeReference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrivilegeReference()
        {
            this.MedecinPrivilege = new HashSet<MedecinPrivilege>();
        }
    
        public int PrivilegeReferenceId { get; set; }
        public string CodePrivilege { get; set; }
        public string LibellePrivilege { get; set; }
        public string Categorie { get; set; }
        public string Description { get; set; }
        public bool NecessiteBlocOperatoire { get; set; }
        public bool NecessiteInstallation { get; set; }
        public bool NecessiteUnite { get; set; }
        public Nullable<int> OrdreAffichage { get; set; }
        public bool EstActif { get; set; }
        public System.DateTime DateCreation { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedecinPrivilege> MedecinPrivilege { get; set; }
    }
}
