//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniteOrganisationnelle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UniteOrganisationnelle()
        {
            this.MedecinUniteOrganisationnelle = new HashSet<MedecinUniteOrganisationnelle>();
            this.UniteOrganisationnelle1 = new HashSet<UniteOrganisationnelle>();
            this.MedecinPrivilege = new HashSet<MedecinPrivilege>();
        }
    
        public int UniteOrganisationnelleId { get; set; }
        public string Libelle { get; set; }
        public string TypeUnite { get; set; }
        public Nullable<int> UniteParentId { get; set; }
        public bool EstActif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedecinUniteOrganisationnelle> MedecinUniteOrganisationnelle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UniteOrganisationnelle> UniteOrganisationnelle1 { get; set; }
        public virtual UniteOrganisationnelle UniteOrganisationnelle2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedecinPrivilege> MedecinPrivilege { get; set; }
    }
}
