//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilisateurMetier
    {
        public int UtilisateurMetierId { get; set; }
        public string IdentifiantSource { get; set; }
        public string Courriel { get; set; }
        public string NomComplet { get; set; }
        public string Connexion { get; set; }
        public string AspNetUserId { get; set; }
        public bool EstActif { get; set; }
    }
}
