//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CotisationsParAnnee
    {
        public int CotisationAnnuelleId { get; set; }
        public int MedecinId { get; set; }
        public string Permis { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public short AnneeExercice { get; set; }
        public string CodeCotisation { get; set; }
        public Nullable<decimal> MontantInitial { get; set; }
        public Nullable<decimal> MontantFinal { get; set; }
        public Nullable<decimal> MontantPaye { get; set; }
        public string EtatCotisation { get; set; }
        public Nullable<System.DateTime> DatePaiement { get; set; }
    }
}
