//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MedecinsRegistreCourant
    {
        public int MedecinId { get; set; }
        public string Permis { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string StatutMedecin { get; set; }
        public string CategoriePratique { get; set; }
        public string Telephone1 { get; set; }
        public string Courriel1 { get; set; }
        public string Installation1Source { get; set; }
        public string Departement1 { get; set; }
        public string ServiceSecteur1 { get; set; }
        public string NominationAdministrativeCourante { get; set; }
        public string FitTestCourant { get; set; }
        public bool EstActif { get; set; }
    }
}
