/*
 * Globalize Culture vi-VN
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "vi-VN", "default", {
	name: "vi-VN",
	englishName: "Vietnamese (Vietnam)",
	nativeName: "Ti�ng Vi?t (Vi?t Nam)",
	language: "vi",
	numberFormat: {
		",": ".",
		".": ",",
		percent: {
			",": ".",
			".": ","
		},
		currency: {
			pattern: ["-n $","n $"],
			",": ".",
			".": ",",
			symbol: "?"
		}
	},
	calendars: {
		standard: {
			firstDay: 1,
			days: {
				names: ["Chu? Nh�?t","Thu� Hai","Thu� Ba","Thu� Tu","Thu� Nam","Thu� Sa�u","Thu� Ba?y"],
				namesAbbr: ["CN","Hai","Ba","Tu","Nam","Sa�u","Ba?y"],
				namesShort: ["C","H","B","T","N","S","B"]
			},
			months: {
				names: ["Tha�ng Gi�ng","Tha�ng Hai","Tha�ng Ba","Tha�ng Tu","Tha�ng Nam","Tha�ng Sa�u","Tha�ng Ba?y","Tha�ng Ta�m","Tha�ng Chi�n","Tha�ng Muo`i","Tha�ng Muo`i M�?t","Tha�ng Muo`i Hai",""],
				namesAbbr: ["Thg1","Thg2","Thg3","Thg4","Thg5","Thg6","Thg7","Thg8","Thg9","Thg10","Thg11","Thg12",""]
			},
			AM: ["SA","sa","SA"],
			PM: ["CH","ch","CH"],
			patterns: {
				d: "dd/MM/yyyy",
				D: "dd MMMM yyyy",
				f: "dd MMMM yyyy h:mm tt",
				F: "dd MMMM yyyy h:mm:ss tt",
				M: "dd MMMM",
				Y: "MMMM yyyy"
			}
		}
	}
});

}( this ));
