/*
 * Globalize Culture sms-FI
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "sms-FI", "default", {
	name: "sms-FI",
	englishName: "Sami, Skolt (Finland)",
	nativeName: "s��m�ki�ll (L��ddj�nnam)",
	language: "sms",
	numberFormat: {
		",": "�",
		".": ",",
		percent: {
			",": "�",
			".": ","
		},
		currency: {
			pattern: ["-n $","n $"],
			",": "�",
			".": ",",
			symbol: "�"
		}
	},
	calendars: {
		standard: {
			"/": ".",
			firstDay: 1,
			days: {
				names: ["p�sspei�vv","vu�ssargg","m��ibargg","se�rad","nelljdpei�vv","pi�tn�c","sue�vet"],
				namesAbbr: ["p�","vu","m�","se","ne","pi","su"],
				namesShort: ["p","v","m","s","n","p","s"]
			},
			months: {
				names: ["oddee�jjm��n","t�lvvm��n","p�zzl�ttamm��n","njuhccm��n","vue�ssm��n","kie�ssm��n","suei�nnm��n","p�rggm��n","c�hccm��n","k�lggm��n","skamm�m��n","rosttovm��n",""],
				namesAbbr: ["odjm","t�lvv","p�zl","njuh","vue","kie","suei","p�r","c�h","k�lg","ska","rost",""]
			},
			monthsGenitive: {
				names: ["oddee�jjmannu","t�lvvmannu","p�zzl�ttammannu","njuhccmannu","vue�ssmannu","kie�ssmannu","suei�nnmannu","p�rggmannu","c�hccmannu","k�lggmannu","skamm�mannu","rosttovmannu",""],
				namesAbbr: ["odjm","t�lvv","p�zl","njuh","vue","kie","suei","p�r","c�h","k�lg","ska","rost",""]
			},
			AM: null,
			PM: null,
			patterns: {
				d: "d.M.yyyy",
				D: "MMMM d'. p. 'yyyy",
				t: "H:mm",
				T: "H:mm:ss",
				f: "MMMM d'. p. 'yyyy H:mm",
				F: "MMMM d'. p. 'yyyy H:mm:ss",
				M: "MMMM d'. p. '",
				Y: "MMMM yyyy"
			}
		}
	}
});

}( this ));
